-- 코드를 입력하세요
SELECT C.USER_ID, C.PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CSA
      FROM ONLINE_SALE 
      GROUP BY USER_ID, PRODUCT_ID
     ) AS C
WHERE C.CSA > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC